name: jdpro-auto-sync

on:
  push:
    branches:
      -master
  workflow_dispatch:
  schedule:
    - cron: 0 */24 * * *   # 每隔12小时
  watch:                                                        # 监视操作
    types: [started]                                            # 点击 Star 之后
jobs:
  update_external_airflow_fork:
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
          github_token: ${{ secrets.ACTION_BUILD_TOKEN }} # 令牌
          upstream_repository: 6dylan6/jdpro  # 上游仓库
          target_repository: dylan8888/jdpro  # 你要推送的仓库
          upstream_branch: main  # 默认是拉取上游仓库的master分支
          target_branch: main  # 默认推送到你的仓库master分支
          force: true  # 是否强制推送
          tags: true  # 确定是否使用-tags